services:
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    restart: on-failure:3
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME:
      KAFKA_CREATE_TOPICS:
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_VERSION: '0.11.0.1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

  zookeeper:
    image: wurstmeister/zookeeper

  tests:
    build:
      context: ../../
      args:
        - GITHUB_TOKEN
        - GOPRIVATE
    working_dir: /src/x/events
    environment:
      KAFKA_ADVERTISED_HOST_NAME:
      TIMEOUT_MULTIPLIER:
      BUILD_TAGS: "-tags musl,integration"
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_ADVERTISED_HOST_NAME}"
    command:
      - make
      - deps
      - test
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
